version: 2
jobs:
  build:
    docker:
      - image: golang:1.16
    steps:
      - checkout
      - run: |
          make build
          git diff --exit-code

  lint:
    docker:
      - image: golang:1.16
    steps:
      - checkout
      - run: |
          apt-get update && apt-get install xz-utils
          make lint --always-make

  test:
    docker:
      - image: golang:1.16
    steps:
      - checkout
      - run: |
          apt-get update && apt-get -y install xz-utils unzip openssl netcat-openbsd
          make test --always-make

  generate:
    docker:
      - image: golang:1.16
    steps:
      - checkout
      - run: |
          make README.md --always-make
          git diff --exit-code

  container-push:
    machine:
      image: ubuntu-2004:202107-02
    steps:
      - checkout
      - run: |
          echo "$DOCKER_PASS" | docker login quay.io --username $DOCKER_USER --password-stdin
          make container-push

  container-release:
    machine:
      image: ubuntu-2004:202107-02
    steps:
      - checkout
      - run: |
          echo "$DOCKER_PASS" | docker login quay.io --username $DOCKER_USER --password-stdin
          make container-release

workflows:
  version: 2
  test-and-push:
    jobs:
      - build
      - lint
      - test
      - generate
